Set environment variables in a dedicated step (#274)

diff --git a/.github/workflows/build-os-images.yaml b/.github/workflows/build-os-images.yaml
--- a/.github/workflows/build-os-images.yaml
+++ b/.github/workflows/build-os-images.yaml
@@ -3,7 +3,6 @@ name: Build OS images
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  TEMP_WORKSPACE_PATH: "/tmp/temp-customize-os-image-workdir"
 
 on:
   push:
@@ -35,6 +34,15 @@ jobs:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2.4.0
+      - name: Set environment variables
+        run: |
+          TEMP_WORKSPACE_PATH="$(mktemp -d)"
+          {
+            echo "TEMP_WORKSPACE_PATH=${TEMP_WORKSPACE_PATH}"
+            echo "BUILD_CONFIGURATION_FILE_NAME=$(basename "${{ matrix.build-configuration-file-path }}")"
+            echo "BUILD_CONFIGURATION_DIRECTORY_PATH=$(dirname "${{ matrix.build-configuration-file-path }}")"
+            echo "RESULTS_FILE_PATH=${TEMP_WORKSPACE_PATH}/results.out"
+          } >>"${GITHUB_ENV}"
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
       - name: Build the OS image builder container image
@@ -48,32 +56,46 @@ jobs:
           tags: "${{ env.OS_BUILDER_CONTAINER_IMAGE_ID }}"
       - name: "Generate the cloud-init datasource ISO. Config: ${{ matrix.build-configuration-file-path }}"
         run: |
-          BUILD_CONFIGURATION_FILE_NAME="$(basename "${{ matrix.build-configuration-file-path }}")"
-          BUILD_CONFIGURATION_DIRECTORY_PATH="$(dirname "${{ matrix.build-configuration-file-path }}")"
-          mkdir -p "${TEMP_WORKSPACE_PATH}"
-
           docker run \
             --privileged \
+            --user "$(id -u):$(id -g)" \
             -v /dev:/dev \
             -v "${TEMP_WORKSPACE_PATH}":/tmp/workdir \
             -v "${BUILD_CONFIGURATION_DIRECTORY_PATH}":/tmp/config \
             "${OS_BUILDER_CONTAINER_IMAGE_ID}" \
             --build-config /tmp/config/"${BUILD_CONFIGURATION_FILE_NAME}"
 
-          RESULTS_FILE_PATH="${TEMP_WORKSPACE_PATH}/results.out"
-          if [ -r "${RESULTS_FILE_PATH}" ]; then
-            echo "Appending the build result metadata file (${RESULTS_FILE_PATH}) contents to GITHUB_ENV..."
-            cat "${RESULTS_FILE_PATH}" >>"${GITHUB_ENV}"
-          else
+          if ! [ -r "${RESULTS_FILE_PATH}" ]; then
             echo "[ERROR]: The build result metadata file is not available at ${RESULTS_FILE_PATH}. Terminating..."
+            exit 2
+          fi
+
+          echo "Sourcing ${RESULTS_FILE_PATH} to load the variables defined there..."
+          # shellcheck source=/dev/null
+          . "${RESULTS_FILE_PATH}"
+
+          CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH="${TEMP_WORKSPACE_PATH}/${CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME}"
+          if ! [ -e "${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}" ]; then
+            echo "Contents of ${TEMP_WORKSPACE_PATH}:"
+            ls -alh "${TEMP_WORKSPACE_PATH}"
+            echo "[ERROR]: The customized compressed image file doesn't exist. Terminating..."
             exit 1
           fi
+
+          echo "Adding the path to the customized compressed image (${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}) file to GITHUB_ENV"
+          {
+            echo "CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH=${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}"
+          } >>"${GITHUB_ENV}"
+
+          echo "Appending the build result metadata file (${RESULTS_FILE_PATH}) contents to GITHUB_ENV..."
+          cat "${RESULTS_FILE_PATH}" >>"${GITHUB_ENV}"
       - uses: actions/upload-artifact@v2
+        name: Upload ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME }}
         with:
           if-no-files-found: error
           name: ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME }}
           path: |
-            ${{ env.TEMP_WORKSPACE_PATH }}/${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME }}
+            ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH }}
     strategy:
       matrix:
         build-configuration-file-path:
